<h2 class="webfont">
	<a href="/friends/list">Friends >> list >> details</a>
</h2>

<form method="post" action="">
	<fieldset>
		<?php $sField = 'email'; echo $this->formField(
			'Email',
			$sField,
			$this->formText($sField, $this->formValue($sField))
		)?>
		<?php $sField = 'phone'; echo $this->formField(
			'Phone',
			$sField,
			$this->formText($sField, $this->formValue($sField))
		)?>
		<?php $sField = 'city'; echo $this->formField(
			'City',
			$sField,
			$this->formText($sField, $this->formValue($sField))
		)?>
		<?php $sField = 'address'; echo $this->formField(
			'Address',
			$sField,
			$this->formText($sField, $this->formValue($sField))
		)?>
	</fieldset>
	<fieldset>
		<button type="submit">save</button>
		<a href="/friends/list">cancel</a>
	</fieldset>
</form>
