<table>
	<thead>
		<tr>
			<td><?php echo $this->sortLink('id') ?></td>
			<td><?php echo $this->sortLink('email') ?></td>
			<td><?php echo $this->sortLink('phone') ?></td>
			<td><?php echo $this->sortLink('city') ?></td>
			<td><?php echo $this->sortLink('address') ?></td>
			<td>actions</td>
		</tr>
	</thead>
	<tbody>

<?php foreach($this->oPaginator as $oItem): ?>
		<tr>
			<td><?php echo $oItem->getId() ?></td>
			<td><?php echo $oItem->getEmail() ?></td>
			<td><?php echo $oItem->getPhone() ?></td>
			<td><?php echo $oItem->getCity() ?></td>
			<td><?php echo $oItem->getAddress() ?></td>
			<td>
				<a href="<?php echo $this->getUrl(['id' => $oItem->getId()], 'edit') ?>">edit</a> |
				<a href="<?php echo $this->getUrl(['id' => $oItem->getId()], 'delete') ?>">del</a>
			</td>
		</tr>
<?php endforeach; ?>

	</tbody>
	<tfoot>
		<tr>
			<td>
				<a href="<?php echo $this->getUrl([], 'add') ?>">+ add</a>
			</td>
		</tr>
	</tfoot>
</table>

<?php echo $this->paginator($this->oPaginator);?>
