<h2 class="webfont">
	<a href="/borrows/list">Borrows >> list</a>
</h2>

<table>
	<thead>
		<tr>
			<td><?php echo $this->sortLink('id') ?></td>
			<td><?php echo $this->sortLink('item') ?></td>
			<td><?php echo $this->sortLink('friend') ?></td>
			<td><?php echo $this->sortLink('start') ?></td>
			<td><?php echo $this->sortLink('end') ?></td>
			<td>actions</td>
		</tr>
	</thead>
	<tbody>

<?php foreach($this->oPaginator as $oItem): ?>
		<tr>
			<td><?php echo $oItem->getId() ?></td>
			<td><?php echo $oItem->getItem()->getName() ?></td>
			<td><?php echo $oItem->getFriend()->getFullName() ?></td>
			<td><?php echo $oItem->getStart() === null ? '' : date('Y-m-d', $oItem->getStart()) ?></td>
			<td><?php echo $oItem->getEnd() === null ? '' : date('Y-m-d', $oItem->getEnd()) ?></td>
			<td>
				<a href="<?php echo $this->getUrl(['id' => $oItem->getId()], 'delete') ?>">del</a>
			</td>
		</tr>
<?php endforeach; ?>

	</tbody>
</table>

<?php echo $this->paginator($this->oPaginator);?>
