<?php if($this->code == 404): ?>
  <h1 class="center">404</h1>
  <h2 class="webfont">Page not found</h2>
<?php elseif($this->code == 403): ?>
  <h1>403</h1>
  <h2>Access deny</h2>
<?php else: ?>
  <h1>500</h1>
  <h2>Ups! Application error</h2>
<?php endif; ?>

<?php if(isset($this->exception)): ?>

  <div class="error-info">
    <h3>Message:</h3>
    <p>
      <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
    </pre>
  </div>

<?php endif; ?>
